### PR TITLE
A licence update.

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by PieGuy7896** [comment]
@buildcarter8

**Comment by buildcarter8** [comment]
Ill think about it

**Comment by buildcarter8** [comment]
@tylerhyperHD @PieGuy7896 should we change this to the license?

**Comment by PieGuy7896** [comment]
@buildcarter8 i think its a nice enhancement

**Comment by DUFCLiam** [comment]
Bump

**Comment by buildcarter8** [comment]
Merged

**Comment by DUFCLiam** [comment]
Finally :P

**Pull request merged**
